export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAILED = 'UPDATE_USER_PROFILE_FAILED';


export const UPDATE_USER_PROFILE_PIC = 'UPDATE_USER_PROFILE_PIC';
export const UPDATE_USER_PROFILE_PIC_SUCCESS = 'UPDATE_USER_PROFILE_PIC_SUCCESS';
export const UPDATE_USER_PROFILE_PIC_FAILED = 'UPDATE_USER_PROFILE_PIC_FAILED';


export const CHANGE_USER_PASSWORD = 'CHANGE_USER_PASSWORD';
export const CHANGE_USER_PASSWORD_SUCCESS = 'CHANGE_USER_PASSWORD_SUCCESS';
export const CHANGE_USER_PASSWORD_FAILED = 'CHANGE_USER_PASSWORD_FAILED';
